LW-67: Dodać przekierowania do profili użytkowników, oraz zmienić ścieżki
RobertKrzywina/team-project pull request #67
Opened 2020-06-02 13:10 UTC by joannabiala

2020-06-02 21:55 UTC, bercik97 requested changes

2020-06-02 21:55 UTC, RobertKrzywina commented on frontend/src/MainPageForLoggedIn.js
> +    const to = "/otheruserprofile/" + notice.authorEmail;
Najlepiej jak URL'e mają postać np. other-user-profile. Adres jest wtedy czytelniejszy, zarówno dla usera jak i dla kogoś kto pisze kod :P

2020-06-02 21:58 UTC, bercik97 requested changes

2020-06-02 21:58 UTC, RobertKrzywina commented on frontend/src/MainPageForLoggedIn.js
> +        <Link to="/userpanel">
^

2020-06-03 09:00 UTC, ghost approved these changes

2020-06-03 09:00 UTC, merged